package com.arkware.ide

import android.Manifest
import android.content.ComponentName
import android.content.Context
import android.content.Intent
import android.content.ServiceConnection
import android.content.pm.PackageManager
import android.os.Build
import android.os.Bundle
import android.os.IBinder
import android.webkit.WebResourceRequest
import android.webkit.WebResourceResponse
import android.webkit.WebView
import android.webkit.WebViewClient
import androidx.activity.result.contract.ActivityResultContracts
import androidx.appcompat.app.AppCompatActivity
import androidx.core.content.ContextCompat
import androidx.core.view.WindowCompat
import androidx.lifecycle.lifecycleScope
import androidx.webkit.WebViewAssetLoader
import com.arkware.ide.backend.IdeBackendService
import com.arkware.ide.backend.IdeBackendState
import com.arkware.ide.logging.ArkLogger
import kotlinx.coroutines.launch

/**
 * Application-mode runtime shell, generated by `arklight android
 * scaffold` (see docs/Backends/ANDROID-BACKEND-IMPLEMENTATION.md,
 * Stage 1), then hand-edited per
 * docs/Foundational/VSCODE-IDE-IMPLEMENTATION-PLAN.md Phase 0/1: the
 * `WebView` now starts on the scaffolded static placeholder page (this
 * project's own `assets/index.html`, ARKlight's own onboarding/error
 * page from section 3 -- not the VS Code workbench) and navigates to
 * `IdeBackendService`'s loopback URL once that service reports it's
 * actually listening, rather than staying on the static page forever.
 *
 * `ArkBundle.kt`/`ArkSeal.kt`/`MemoryGuard.kt` ship alongside this
 * file (vendored unchanged from the Viewer app) but go unused by this
 * code path -- see ANDROID-BACKEND-IMPLEMENTATION.md's "Open
 * questions for Stage 0", "Packed .ark vs. unpacked tree".
 */
class MainActivity : AppCompatActivity() {

    private lateinit var webView: WebView
    private var backendService: IdeBackendService? = null
    private var navigatedToBackend = false

    private val notificationPermissionLauncher =
        registerForActivityResult(ActivityResultContracts.RequestPermission()) { granted ->
            if (!granted) {
                // Not fatal: the backend still starts and the
                // port-handoff still works without a notification --
                // Android just won't let the service promote itself
                // to foreground with a visible notice. Logged, not
                // silently dropped, per CODE-STYLE.md section 3.
                ArkLogger.w(message = "MainActivity: notification permission denied; " +
                    "IdeBackendService will run without a visible notification")
            }
        }

    private val connection = object : ServiceConnection {
        override fun onServiceConnected(name: ComponentName, service: IBinder) {
            val bound = (service as IdeBackendService.LocalBinder).service()
            backendService = bound
            lifecycleScope.launch {
                bound.state.collect { state -> onBackendState(state) }
            }
        }

        override fun onServiceDisconnected(name: ComponentName) {
            backendService = null
        }
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        WindowCompat.setDecorFitsSystemWindows(window, false)
        webView = WebView(this)
        setContentView(webView)

        webView.settings.javaScriptEnabled = true
        webView.settings.domStorageEnabled = true

        val assetLoader = WebViewAssetLoader.Builder()
            .addPathHandler("/assets/", WebViewAssetLoader.AssetsPathHandler(this))
            .build()

        webView.webViewClient = object : WebViewClient() {
            override fun shouldInterceptRequest(
                view: WebView,
                request: WebResourceRequest
            ): WebResourceResponse? {
                // Only the static placeholder page is served through
                // the asset loader's virtual origin; once navigated to
                // the backend's real http://127.0.0.1:<port>/ origin,
                // this handler simply returns null (no interception)
                // for every request, letting WebView's normal network
                // stack handle it instead -- the two origins are never
                // mixed within a single loaded page.
                return assetLoader.shouldInterceptRequest(request.url)
            }
        }

        webView.loadUrl(PLACEHOLDER_URL)

        ensureNotificationPermission()
        startAndBindBackend()
    }

    override fun onDestroy() {
        unbindService(connection)
        // Deliberately not stopService()'d here: the backend is meant
        // to keep running (and keep whatever terminal/session state
        // it holds alive) across an Activity recreation, e.g. a
        // rotation or the user briefly switching apps -- see
        // network_security_config.xml's loopback-only scoping, which
        // is what makes this safe to leave running.
        super.onDestroy()
    }

    @Suppress("DEPRECATION")
    override fun onBackPressed() {
        if (webView.canGoBack()) webView.goBack() else super.onBackPressed()
    }

    // ---- backend wiring --------------------------------------------------

    private fun ensureNotificationPermission() {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.TIRAMISU) return
        val granted = ContextCompat.checkSelfPermission(
            this,
            Manifest.permission.POST_NOTIFICATIONS
        ) == PackageManager.PERMISSION_GRANTED
        if (!granted) {
            notificationPermissionLauncher.launch(Manifest.permission.POST_NOTIFICATIONS)
        }
    }

    private fun startAndBindBackend() {
        val intent = Intent(this, IdeBackendService::class.java)
        ContextCompat.startForegroundService(this, intent)
        bindService(intent, connection, Context.BIND_AUTO_CREATE)
    }

    private fun onBackendState(state: IdeBackendState) {
        when (state) {
            is IdeBackendState.Starting -> Unit // already on the placeholder page
            is IdeBackendState.Ready -> {
                if (navigatedToBackend) return
                navigatedToBackend = true
                ArkLogger.d(message = "MainActivity: backend ready on port ${state.port}, navigating")
                webView.loadUrl("http://127.0.0.1:${state.port}/")
            }
            is IdeBackendState.Failed -> {
                ArkLogger.e(message = "MainActivity: backend failed to start: ${state.reason}")
                // Stays on the placeholder page -- that page's own
                // copy ("Starting the local IDE backend...") is not
                // yet failure-specific; a distinct failure state for
                // that page is a follow-up once there's a real backend
                // whose failure modes are worth distinguishing in the
                // UI (see VSCODE-IDE-IMPLEMENTATION-PLAN.md section 4.5
                // for the kinds of failures Phase 3+ actually needs to
                // surface here).
            }
        }
    }

    companion object {
        private const val PLACEHOLDER_URL = "https://appassets.androidplatform.net/assets/index.html"
    }
}
