package com.arkware.ide

import android.Manifest
import android.content.ComponentName
import android.content.Context
import android.content.Intent
import android.content.ServiceConnection
import android.content.pm.PackageManager
import android.os.Build
import android.os.Bundle
import android.os.IBinder
import android.view.Gravity
import android.view.ViewGroup
import android.webkit.WebResourceRequest
import android.webkit.WebResourceResponse
import android.webkit.WebView
import android.webkit.WebViewClient
import android.widget.FrameLayout
import androidx.activity.result.contract.ActivityResultContracts
import androidx.appcompat.app.AppCompatActivity
import androidx.core.content.ContextCompat
import androidx.core.view.WindowCompat
import androidx.lifecycle.lifecycleScope
import androidx.webkit.WebViewAssetLoader
import com.arkware.ide.backend.IdeBackendService
import com.arkware.ide.backend.IdeBackendState
import com.arkware.ide.logging.ArkLogger
import com.arkware.ide.workspace.WorkspaceManager
import com.google.android.material.button.MaterialButton
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext

/**
 * Application-mode runtime shell, generated by `arklight android
 * scaffold` (see docs/Backends/ANDROID-BACKEND-IMPLEMENTATION.md,
 * Stage 1), then hand-edited per
 * docs/Foundational/VSCODE-IDE-IMPLEMENTATION-PLAN.md Phase 0/1: the
 * `WebView` now starts on the scaffolded static placeholder page (this
 * project's own `assets/index.html`, ARKlight's own onboarding/error
 * page from section 3 -- not the VS Code workbench) and navigates to
 * `IdeBackendService`'s loopback URL once that service reports it's
 * actually listening, rather than staying on the static page forever.
 *
 * `ArkBundle.kt`/`ArkSeal.kt`/`MemoryGuard.kt` ship alongside this
 * file (vendored unchanged from the Viewer app) but go unused by this
 * code path -- see ANDROID-BACKEND-IMPLEMENTATION.md's "Open
 * questions for Stage 0", "Packed .ark vs. unpacked tree".
 *
 * Also owns the plan's section 6 SAF wiring: [openWorkspaceLauncher]
 * is the `ActivityResultContracts.OpenDocumentTree()` registration
 * that has to live on an Activity (unlike the rest of that section's
 * logic, which is [WorkspaceManager]'s job), and [prepareWorkspaceThenStartBackend]
 * is what makes sure [IdeBackendService] always gets a real,
 * already-synced sandbox directory to open -- picked workspace or
 * not -- before it's ever started.
 */
class MainActivity : AppCompatActivity() {

    private lateinit var webView: WebView
    private lateinit var workspaceManager: WorkspaceManager
    private var backendService: IdeBackendService? = null
    private var navigatedToBackend = false

    private val notificationPermissionLauncher =
        registerForActivityResult(ActivityResultContracts.RequestPermission()) { granted ->
            if (!granted) {
                // Not fatal: the backend still starts and the
                // port-handoff still works without a notification --
                // Android just won't let the service promote itself
                // to foreground with a visible notice. Logged, not
                // silently dropped, per CODE-STYLE.md section 3.
                ArkLogger.w(message = "MainActivity: notification permission denied; " +
                    "IdeBackendService will run without a visible notification")
            }
        }

    private val openWorkspaceLauncher =
        registerForActivityResult(ActivityResultContracts.OpenDocumentTree()) { uri ->
            if (uri == null) {
                ArkLogger.d(message = "MainActivity: workspace folder pick cancelled")
                return@registerForActivityResult
            }
            lifecycleScope.launch {
                workspaceManager.persistTreeUri(uri)
                withContext(Dispatchers.IO) { workspaceManager.syncIn(uri) }
                ArkLogger.d(message = "MainActivity: workspace synced in from $uri")
            }
        }

    private val connection = object : ServiceConnection {
        override fun onServiceConnected(name: ComponentName, service: IBinder) {
            val bound = (service as IdeBackendService.LocalBinder).service()
            backendService = bound
            lifecycleScope.launch {
                bound.state.collect { state -> onBackendState(state) }
            }
        }

        override fun onServiceDisconnected(name: ComponentName) {
            backendService = null
        }
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        WindowCompat.setDecorFitsSystemWindows(window, false)
        workspaceManager = WorkspaceManager(this)

        webView = WebView(this)
        webView.settings.javaScriptEnabled = true
        webView.settings.domStorageEnabled = true

        val assetLoader = WebViewAssetLoader.Builder()
            .addPathHandler("/assets/", WebViewAssetLoader.AssetsPathHandler(this))
            .build()

        webView.webViewClient = object : WebViewClient() {
            override fun shouldInterceptRequest(
                view: WebView,
                request: WebResourceRequest
            ): WebResourceResponse? {
                // Only the static placeholder page is served through
                // the asset loader's virtual origin; once navigated to
                // the backend's real http://127.0.0.1:<port>/ origin,
                // this handler simply returns null (no interception)
                // for every request, letting WebView's normal network
                // stack handle it instead -- the two origins are never
                // mixed within a single loaded page.
                return assetLoader.shouldInterceptRequest(request.url)
            }
        }

        webView.loadUrl(PLACEHOLDER_URL)
        setContentView(buildRootView())

        ensureNotificationPermission()
        lifecycleScope.launch { prepareWorkspaceThenStartBackend() }
    }

    override fun onStop() {
        super.onStop()
        // Best-effort periodic sync (plan section 6, "copy changes
        // back out on save/close/periodic sync") -- fires whenever the
        // user leaves the app, not just on a final close. Runs on
        // lifecycleScope so it's cancelled if the Activity is fully
        // destroyed shortly after, same as any other lifecycle-scoped
        // work; a stricter guarantee than that isn't worth adding for
        // an MVP sync path.
        val treeUri = workspaceManager.persistedTreeUri() ?: return
        lifecycleScope.launch(Dispatchers.IO) { workspaceManager.syncOut(treeUri) }
    }

    override fun onDestroy() {
        unbindService(connection)
        // Deliberately not stopService()'d here: the backend is meant
        // to keep running (and keep whatever terminal/session state
        // it holds alive) across an Activity recreation, e.g. a
        // rotation or the user briefly switching apps -- see
        // network_security_config.xml's loopback-only scoping, which
        // is what makes this safe to leave running.
        super.onDestroy()
    }

    // ---- workspace (SAF) wiring -------------------------------------------

    /**
     * Wraps [webView] plus a small always-available "open folder"
     * button (see class doc) in a plain `FrameLayout` -- the theme is
     * `NoActionBar` (WebView fills the whole window, see themes.xml),
     * so an overflow menu isn't an option without a bigger layout
     * change than this feature needs; an overlay button re-uses the
     * Material dependency already pulled in for dynamic color.
     */
    private fun buildRootView(): FrameLayout {
        val root = FrameLayout(this)
        root.addView(
            webView,
            FrameLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT),
        )

        val openFolderButton = MaterialButton(this).apply {
            text = getString(R.string.open_workspace_folder)
            setOnClickListener { openWorkspaceLauncher.launch(null) }
        }
        val margin = (16 * resources.displayMetrics.density).toInt()
        val buttonParams = FrameLayout.LayoutParams(
            ViewGroup.LayoutParams.WRAP_CONTENT,
            ViewGroup.LayoutParams.WRAP_CONTENT,
        ).apply {
            gravity = Gravity.BOTTOM or Gravity.END
            setMargins(margin, margin, margin, margin)
        }
        root.addView(openFolderButton, buttonParams)
        return root
    }

    /**
     * Runs once per Activity creation, before the backend is ever
     * started: if a workspace folder was picked on a previous launch,
     * re-syncs it into the sandbox copy (section 6's copy-in step) so
     * edits made outside the app since last run are picked up. Either
     * way the backend always gets a real, already-existing directory
     * to open -- an unpicked workspace is simply an empty sandbox
     * folder, never a hard blocker on startup, since code-server
     * itself supports opening with no folder at all.
     */
    private suspend fun prepareWorkspaceThenStartBackend() {
        val treeUri = workspaceManager.persistedTreeUri()
        if (treeUri != null) {
            withContext(Dispatchers.IO) { workspaceManager.syncIn(treeUri) }
        }
        startAndBindBackend(workspaceManager.sandboxWorkspaceDir.absolutePath)
    }

    @Suppress("DEPRECATION")
    override fun onBackPressed() {
        if (webView.canGoBack()) webView.goBack() else super.onBackPressed()
    }

    // ---- backend wiring --------------------------------------------------

    private fun ensureNotificationPermission() {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.TIRAMISU) return
        val granted = ContextCompat.checkSelfPermission(
            this,
            Manifest.permission.POST_NOTIFICATIONS
        ) == PackageManager.PERMISSION_GRANTED
        if (!granted) {
            notificationPermissionLauncher.launch(Manifest.permission.POST_NOTIFICATIONS)
        }
    }

    private fun startAndBindBackend(workspaceDir: String) {
        val intent = Intent(this, IdeBackendService::class.java)
            .putExtra(IdeBackendService.EXTRA_WORKSPACE_DIR, workspaceDir)
        ContextCompat.startForegroundService(this, intent)
        bindService(intent, connection, Context.BIND_AUTO_CREATE)
    }

    private fun onBackendState(state: IdeBackendState) {
        when (state) {
            is IdeBackendState.Starting -> Unit // already on the placeholder page
            is IdeBackendState.Ready -> {
                if (navigatedToBackend) return
                navigatedToBackend = true
                ArkLogger.d(message = "MainActivity: backend ready on port ${state.port}, navigating")
                webView.loadUrl("http://127.0.0.1:${state.port}/")
            }
            is IdeBackendState.Failed -> {
                ArkLogger.e(message = "MainActivity: backend failed to start: ${state.reason}")
                // Stays on the placeholder page -- that page's own
                // copy ("Starting the local IDE backend...") is not
                // yet failure-specific; a distinct failure state for
                // that page is a follow-up once there's a real backend
                // whose failure modes are worth distinguishing in the
                // UI (see VSCODE-IDE-IMPLEMENTATION-PLAN.md section 4.5
                // for the kinds of failures Phase 3+ actually needs to
                // surface here).
            }
        }
    }

    companion object {
        private const val PLACEHOLDER_URL = "https://appassets.androidplatform.net/assets/index.html"
    }
}
